baseURL: 'http://philibert.hugo'
DefaultContentLanguage: en
MetaDataFormat: yaml
title: Regis Philibert
enableRobotsTXT: true
buildDrafts: false
pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
module:
  imports:
    - path: github.com/regisphilibert/rp_hugo_theme
#   - disable: false
#     ignoreConfig: true
#     path: github.com/regisphilibert/mod-content-test
#     mounts:
#     - source: content/test
#       target: content/note
related:
  includeNewer: true
  indices:
    - name: tags
      weight: 100
      toLower: true
    - name: date
      weight: 10
      pattern: 2006

blackfriday:
  extensions:
    - hardLineBreak
  hrefTargetBlank: true

outputFormats:
  markdown:
    baseName: markdown
    mediaType: "text/html"
      
taxonomies:
  tag: tags
  category: categories
  project_tag: project_tags
 
permalinks:
  post: 'blog/:year/:month/:slug/'

imaging:
  resampleFilter: box
  quality: 80